name: Master Workflow

on:
  push:
    branches:
      - main

jobs:
  tag_generator:
    name: Tag Generator
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.tag_version.outputs.new_tag  }}
    steps:   
      - name: Automatic Tag (Bump version and push tag)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches : "main"
  
  print_tag:
    name: Print tag
    runs-on: ubuntu-latest
    needs:
      - tag_generator
    steps:
    - name: Use variables
      run: |
        echo "VERSION: ${{ needs.tag_generator.outputs.new-tag }}"